calkit/calkit-cloud

- backend/Dockerfile
- backend/app/api/routes/projects.py
- backend/pyproject.toml
- backend/uv.lock
- frontend/src/client/models.ts
- frontend/src/client/schemas.ts
- frontend/src/components/Publications/NewPublication.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/files.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/index.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/publications.tsx
- frontend/src/routes/_layout/settings.tsx
- frontend/src/routes/zenodo-auth.tsx
The goal is to make it easier to perform these common actions.
> Add quick actions to project homepage

- frontend/src/components/Projects/CreateProject.tsx
- frontend/src/components/Projects/CreateProjectFromGitHub.tsx
> Navigate to project homepage after creating a new one

- backend/app/api/routes/projects.py
- frontend/src/client/services.ts
- frontend/src/components/Common/Markdown.tsx
- frontend/src/hooks/useProject.ts
- frontend/src/routes/_layout/$userName/$projectName/_layout.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/index.tsx
> Add reproducibility check to project homepage

- docker-compose.override.yml
- docker-compose.yml
The upgrade to uv changed the Dockerfile such that this didn't work properly for CD.
> Add prestart service

- frontend/src/routes/_layout/$userName/$projectName/_layout/notebooks.tsx
> Set max width for notebook filepaths

- backend/app/api/routes/projects.py
- frontend/src/client/models.ts
- frontend/src/client/schemas.ts
- frontend/src/client/services.ts
- frontend/src/components/Common/SidebarItems.tsx
- frontend/src/routeTree.gen.ts
- frontend/src/routes/_layout/$userName/$projectName/_layout.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/app.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/datasets.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/notebooks.tsx
Needs to be hosted somewhere that we can embed in an iframe like Hugging Face Spaces.
> Add ability to define an app for a project

- backend/app/api/deps.py
- backend/app/api/routes/datasets.py
- backend/app/api/routes/projects.py
- backend/app/core.py
- backend/app/git.py
- backend/app/projects.py
- frontend/src/components/Common/Markdown.tsx
- frontend/src/components/Common/SidebarItems.tsx
- frontend/src/components/Common/Topbar.tsx
- frontend/src/components/Files/SelectedItemInfo.tsx
- frontend/src/components/Projects/CreateProject.tsx
- frontend/src/hooks/useAuth.ts
- frontend/src/hooks/useProject.ts
- frontend/src/routes/_layout.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/datasets.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/figures.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/files.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/index.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/publications.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/workflow.tsx
- frontend/src/routes/_layout/admin.tsx
- frontend/src/routes/_layout/index.tsx
- frontend/src/routes/_layout/projects.tsx
- frontend/src/routes/_layout/settings.tsx
> Allow non-authenticated users to view public projects

- backend/app/api/routes/projects.py
- backend/app/models.py
- backend/app/projects.py
> Refactor repo contents fetching for less redundancy

- backend/app/projects.py
> Use presigned URLs for large-ish repo contents; resolves #301

- backend/app/api/routes/login.py
- backend/app/users.py
> Refine logging for GitHub token requests

- backend/app/users.py
> Use with for update to select user GitHub token

- backend/app/git.py
- backend/app/users.py
> Properly complete token transaction

- backend/app/api/routes/users.py
- backend/app/users.py
Discovered #341 along the way here.
> Add API endpoint to fetch user Zenodo token

- Makefile
- backend/Makefile
- backend/app/api/routes/projects.py
- backend/app/subscriptions.py
- backend/app/tests/test_db.py
- backend/pyproject.toml
- backend/uv.lock
- frontend/Makefile
- frontend/src/client/models.ts
- frontend/src/client/schemas.ts
- frontend/src/client/services.ts
- frontend/src/components/Common/SidebarItems.tsx
- frontend/src/components/Environments/ViewEnvironment.tsx
- frontend/src/components/Projects/HelpContent.tsx
- frontend/src/hooks/useProject.ts
- frontend/src/routeTree.gen.ts
- frontend/src/routes/_layout/$userName/$projectName/_layout.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout/environments.tsx
> Add environments page to projects

- backend/app/api/routes/projects.py
- backend/app/dvc.py
- backend/app/models/core.py
For https://github.com/calkit/calkit/pull/254
This also allows us to filter paths in the dataset.
> Allow fetching dataset details for import even when they are in Git

- frontend/src/components/Common/Sidebar.tsx
- frontend/src/components/Projects/CloneProject.tsx
- frontend/src/components/Projects/HelpContent.tsx
- frontend/src/routes/_layout/$userName/$projectName/_layout.tsx
- frontend/src/routes/_layout/learn.tsx
This can be accessed from the project menu:
There are also instructions on the project homepage help:
Resolves #336
> Add instructions for how to clone project with CLI

- backend/app/api/routes/datasets.py
- frontend/src/client/models.ts
- frontend/src/client/schemas.ts
- frontend/src/client/services.ts
- frontend/src/routes/_layout/datasets.tsx
> Allow searching for datasets

- backend/app/api/routes/projects.py
- backend/app/git.py
- backend/pyproject.toml
- backend/uv.lock
Seeing some 404s in production because of this.
> Process includes when getting environments from calkit.yaml and make git repo fetching more robust

- backend/app/api/routes/orgs.py
- backend/uv.lock
- frontend/src/components/Common/Topbar.tsx
- frontend/src/components/Orgs/NewOrg.tsx
> Add ability to import an organization from GitHub

- backend/app/api/routes/orgs.py
- backend/app/api/routes/projects.py
> Attempt to create org and subscription when importing a repo from one

- backend/app/api/routes/projects.py
- frontend/package-lock.json
- frontend/src/client/models.ts
- frontend/src/client/schemas.ts
- frontend/src/components/Projects/MakeProjectPublic.tsx
- frontend/src/routeTree.gen.ts
- frontend/src/routes/_layout/$userName/$projectName/_layout.tsx
Resolves #263, but doesn't implement the ability to share a project with someone that has no account. That will need to be a separate issue.
> Add ability to make a project public

- backend/Dockerfile
- backend/app/api/routes/orgs.py
> More robustly detect org display name
